name: DamageSmpCore
main: org.damagesmpcore.damageSmpCore.DamageSmpCore
version: 1.0.0
api-version: 1.17
description: Dynamic PvP damage boost on kill / penalty on death.
author: FinalCarnage942

commands:
  damage:
    description: View or manage your (or others’) damage percentage, or reload config.
    usage:
      - /damage
      - /damage <player> <set|reset> [value]
      - /damage reload
    permission: damagesmpcore.command.damage
permissions:
  damagesmpcore.command.damage:
    default: op
    description: Allows use of /damage management & reload.
